Add linters error
ecekpo/Book-Store pull request #5
Opened 2022-09-20 19:49 UTC by ecekpo

**Added**
State immutable in reducers
Default state in my books reducer from an empty array to an array with a few books
Imported Redux Provider and store in the main component of React app
Connected app to the Redux store.
Added functionality for "Add new" button click
-Added functionality for "Remove" button click
Added a functionality for "Check status" button click

2022-09-20 21:04 UTC, FrederickMih requested changes
Hi @ecekpo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

_**You almost made it!**_ :rocket: :rocket: 

![](https://media.giphy.com/media/l46CxmW82zcQiRghG/giphy.gif)

## Highlights :green_circle: 

:fast_forward: GitHub workflow has been followed :heavy_check_mark: 
:fast_forward: PR has a summary :+1: 
:fast_forward: Descriptive README.md file :heavy_check_mark: 

## Required Changes ♻️ :red_circle: 

- [ ] Your Pull Request title doesn't reflect what you are implementing @ecekpo. Take a look at the screenshot below:

![Screenshot from 2022-09-20 21-56-11](https://user-images.githubusercontent.com/63087491/191363104-982dbe81-5ed2-4ded-b7ff-3b464a445ec0.png)

In this Milestone, you are implementing **Bookstore: use Redux in React components.**. This is exactly how the title of this PR should reflect. `Add linters error` has nothing to do with this PR :angry: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 21:04 UTC, FrederickMih commented on src/components/Categories.jsx
> +        <button type="submit" onClick={() => dispatch(bookStatus())}>Check Status</button>
- [ ] Based on the requirements of this project, this button should **use** a function `checkCategoriesStatus`(name can be different) made in this component(Categories):  I'll kindly advise you to rectify this.  Let's have a function with a name and call it inside this component. You have already done something fantastic of this sort inside the `Form` component :+1: 


- [ ] It seems this button does not render on the page. If I'm correct then kindly make sure that this button is working as expected.


Thanks :pray:

2022-09-20 21:04 UTC, FrederickMih commented on src/components/Books.jsx
> +// import Header from './Header';
- [ ] Hi @ecekpo, comments render your codebase messy. Let's not commit them to our repo. In case you need a previous version of your work, kindly use git history.

2022-09-20 21:04 UTC, FrederickMih commented on src/components/Books.jsx
> +      <header />
- **Hint** You commented the Header component up because you misspelled it here when rendering it. Instead of `<header />`, you should have had  `<Header />`

2022-09-21 06:12 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @ecekpo,

Nice job making the required changes. Unfortunately, you missed some of them but you are almost there.

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] You have a typo error in the categories route in `Navbar.js` component its supposed to be `categories` instead of `categroies` in line 10. So please fix that because the categories component not rendering now.
https://github.com/ecekpo/Book-Store/blob/391c331aec49fa473c9703aaf1889445b0909f6b/src/components/Navbar.js#L10

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-21 07:04 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @ecekpo,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-21 07:43 UTC, merged